# Generated by Django 5.1.7 on 2025-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="party",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
