# Generated by Django 5.1.7 on 2025-04-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0004_electiontype_alter_election_election_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="voter",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Oczekujące"),
                    ("approved", "Zatwierdzone"),
                    ("rejected", "Odrzucone"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="eligible",
            field=models.BooleanField(default=False),
        ),
    ]
