# Generated by Django 5.1.7 on 2025-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0005_voter_address_voter_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
