# Generated by Django 5.1.7 on 2025-04-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0007_voter_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voter",
            name="user",
        ),
    ]
