# Generated by Django 5.1.7 on 2025-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0009_voter_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
