# Generated by Django 5.1.7 on 2025-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0010_alter_voter_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
