# Generated by Django 5.1.7 on 2025-04-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0012_alter_voter_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="pesel_num",
            field=models.CharField(max_length=11),
        ),
    ]
