# Generated by Django 5.1.7 on 2025-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0013_alter_voter_pesel_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
