# Generated by Django 5.1.7 on 2025-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wybory", "0014_election_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
