# Generated by Django 5.2.1 on 2025-05-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0016_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
    ]
