# Generated by Django 5.2.1 on 2025-05-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0017_remove_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='wybory.election'),
        ),
    ]
