# Generated by Django 5.2.1 on 2025-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0019_partyvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
