# Generated by Django 5.2.1 on 2025-06-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0020_voter_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
        migrations.AddField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='party_images/'),
        ),
    ]
