# Generated by Django 5.2.3 on 2025-06-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wybory', '0021_candidate_image_party_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotersLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wybory.voter')),
            ],
            options={
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
